version: "3.8"

services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 5173:5173
